//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.12 at 10:10:02 AM MST 
//


package xml.newformat.beans.treatment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for treatment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="treatment">
 *   &lt;complexContent>
 *     &lt;extension base="{}treatment">
 *       &lt;redefine>
 *         &lt;complexType name="treatment">
 *           &lt;complexContent>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;sequence>
 *                 &lt;element ref="{}meta"/>
 *                 &lt;element ref="{}taxon_identification" maxOccurs="unbounded"/>
 *               &lt;/sequence>
 *             &lt;/restriction>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}synonym" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}material" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}discussion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}taxon_relation_articulation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}habitat_elevation_distribution_or_ecology" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "treatment", propOrder = {
    "descriptionOrTypeOrSynonym"
})
public class Treatment
    extends OriginalTreatment
{

    @XmlElements({
        @XmlElement(name = "description", type = Description.class),
        @XmlElement(name = "type", type = Type.class),
        @XmlElement(name = "synonym", type = String.class),
        @XmlElement(name = "material", type = Material.class),
        @XmlElement(name = "discussion", type = Discussion.class),
        @XmlElement(name = "taxon_relation_articulation", type = TaxonRelationArticulation.class),
        @XmlElement(name = "habitat_elevation_distribution_or_ecology", type = HabitatElevationDistributionOrEcology.class)
    })
    protected List<Object> descriptionOrTypeOrSynonym;

    /**
     * Gets the value of the descriptionOrTypeOrSynonym property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionOrTypeOrSynonym property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptionOrTypeOrSynonym().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * {@link Type }
     * {@link String }
     * {@link Material }
     * {@link Discussion }
     * {@link TaxonRelationArticulation }
     * {@link HabitatElevationDistributionOrEcology }
     * 
     * 
     */
    public List<Object> getDescriptionOrTypeOrSynonym() {
        if (descriptionOrTypeOrSynonym == null) {
            descriptionOrTypeOrSynonym = new ArrayList<Object>();
        }
        return this.descriptionOrTypeOrSynonym;
    }

}
